networks:
  auth-example:
    name: auth-example

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    networks:
      - auth-example

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - auth-example
